repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4 # keep in sync with pyproject.toml
    hooks:
      - id: ruff
        name: Run linter
      - id: ruff-format
        name: Run formatter
        args: ["--check"]
  - repo: local
    hooks:
      - id: python-license-headers
        name: Fix Python license headers
        entry: python scripts/check_python_license_headers.py --fix
        language: system
        types: [python]
