name: "Install uv"
description: "Install Python and uv"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Set up uv
      uses: astral-sh/setup-uv@v6

    - name: Install dependencies
      shell: bash
      run: uv sync --extra dev
